### PR TITLE
Added board manifest for Atmel at90pwm316

### PR DESCRIPTION
**Pull request by ThingEngineer**

### CODE REVIEW

**Comment by ivankravets** [comment]
Did you test it?

**Comment by ThingEngineer** [comment]
@ivankravets My apologies, I knew I forgot something in the comment before I left. Yes, this is tested and working. I am currently using it in [this project](https://github.com/ThingEngineer/ReactorForge/tree/master/firmware/CriticalMass) making use of the project/boards local copy of the board manifest. The code compiles and programs the device using a USBasp clone with no errors or warnings.

**Comment by ThingEngineer** [comment]
On a related topic, I will get to adding the other AT90PWM{X...} chips as soon as I can.

**Comment by ivankravets** [comment]
Thanks!

**Pull request merged**
