### PR TITLE
Add all MiniCore targets to boards list

### PR DESCRIPTION
**Pull request by MCUdude**
Is this an acceptable format? If so, it's not much work to add my other Arduino cores as well.

### CODE REVIEW

**Comment by MCUdude** [comment]
@ivankravets any thoughts? Is this OK? Seems like your CIs doesn't like this though...

**Comment by ivankravets** [comment]
Thank you so much for the PR! Everything is OK! See https://travis-ci.org/platformio/platform-atmelavr/jobs/536283620#L2337

There is no source code for `MiniCore`. Need to update package.

Could you provide PR to https://github.com/platformio/platformio-pkg-framework-arduinoavr?

**Comment by ivankravets** [comment]
Last thing... Can we keep "name" for DEVICE in upper case? `"name": "ATmega328",` => `"name": "ATMEGA328",`, etc..

**Comment by MCUdude** [comment]
> Could you provide PR to https://github.com/platformio/platformio-pkg-framework-arduinoavr?

Sure. I'll do it as soon as I can. First I'll do a new MiniCore release to keep better track at what versions are used with PlatformIO.

> Last thing... Can we keep "name" for DEVICE in upper case? "name": "ATmega328", => "name": "ATMEGA328",, etc..

Sure thing. However, ATmega328 isn't wrong either, since Microchip/Atmel writes it this way. But if you prefer all upper case letters that's completely fine 👍

**Comment by ivankravets** [comment]
> First I'll do a new MiniCore release to keep better track at what versions are used with PlatformIO.

We use stable releases. Please use the same.

> But if you prefer all upper case letters that's completely fin

This is normal practice for IAR, Keil, Segger, etc to list devices in UPPERCASE.

**Comment by MCUdude** [comment]
I assume we will do all this with MightyCore as well pretty soon to match the new format. I can submit a separate PR for these files after this one is closed if that's OK for you?

In the future, will it be you (as in someone in the PlatformIO team) or me that will have to push new releases to *platformio/platformio-pkg-framework-arduinoavr*?

**Comment by ivankravets** [comment]
I would be better if provide updated releases to https://github.com/platformio/platformio-pkg-framework-arduinoavr/pulls ;)

**Comment by ivankravets** [comment]
I've just added support for MiniCore. See https://github.com/platformio/platformio-pkg-framework-arduinoavr/commit/6a25e00ea2f3cdddb04fbc86e6e591cd82fc164a

Would be thankful for pinging me next time when you will update it.

Thanks!

**Comment by MCUdude** [comment]
Sorry, I was supposed to provide a PR on Friday. But I've been away for the weekend and I didn't have time to prepare the R before I had to leave.

Next time, would you like me to ping you or to provide a PR?

**Comment by ivankravets** [comment]
You can ping me. I'll update if have time. Does it work with the upstream version?
- http://docs.platformio.org/en/latest/platforms/atmelavr.html#upstream

**Comment by MCUdude** [comment]
I haven't been able to test it yet. I'll see if I could do it tonight

**Pull request merged**
