### PR TITLE
Update board files for MightyCore compitable microcontrollers

### PR DESCRIPTION
**Pull request by MCUdude**
This will make all MightyCore compatible microcontrollers "behave" the same way as MiniCore compatible ones.

### CODE REVIEW

**Comment by MCUdude** [comment]
@ivankravets is this PR OK? Anything you'd like me to change?
When this is merged, could you also upgrade MightyCore to [v2.0.2](https://github.com/MCUdude/MightyCore/releases/tag/v2.0.2)?

**Comment by ivankravets** [comment]
Sorry, that disturb you :( I remember I asked you to make device ID in upper case. It seems that ATmega devices do not look very well in upper case. I've just checked IAR device registry -> https://www.iar.com/search-results/#!?query=&devices_architecture=AVR&devices_family=ATmega&tab=devices

Maybe, it makes sense to have the same device IDs? Could you update this PR with the same IDs?

**Comment by ivankravets** [comment]
> When this is merged, could you also upgrade MightyCore to v2.0.2?

I did that in https://github.com/platformio/platform-atmelavr/commit/79e5ef5aa05f68f3fe3a2599251f8d5e31084c99

**Comment by MCUdude** [comment]
First, I did prepare the MegaCore target files in my own fork, and suddenly they have been added to this PR. That was not intended. Do you know how I remove these files from this PR?

> Maybe, it makes sense to have the same device IDs? Could you update this PR with the same IDs?

So do you want me, for instance, to rename ATMEGA1284P to ATmega1284P? How about all the MiniCore targets?

**Comment by ivankravets** [comment]
> Do you know how I remove these files from this PR?

I propose to close this PR and make a new with modified files.

> So do you want me, for instance, to rename ATMEGA1284P to ATmega1284P? How about all the MiniCore targets?

Yes. I actually propose to use the same device IDs as IAR. They are a leader in this market and developers are familiar with their device naming. What do you think?

P.S: We will do the same for STM32, etc.

**Comment by MCUdude** [comment]
Sure! Is it OK if I do a new (giant) PR with:

* All named fixed for all MiniCore targets
* Add MegaCore targets
* Fix MightyCore files as well
?

**Comment by ivankravets** [comment]
>  I do a new (giant) PR with

Great! Please make a new PR.

**Comment by MCUdude** [comment]
You want me to change the file names as well, right?

**Comment by ivankravets** [comment]
Yes, fully adapt them with IAR naming policy, including previous device IDs for MightyCore.

**Comment by MCUdude** [comment]
Great! Meanwhile, you can add MegaCore [v2.0.2](https://github.com/MCUdude/MegaCore/releases/tag/v2.0.2) to PlatformIO if you like 🙂

**Pull request closed without merging**
