### PR TITLE
Add and rename MCUdude AVR targets

### PR DESCRIPTION
**Pull request by MCUdude**

### CODE REVIEW

**Comment by ivankravets** [comment]
- Could we rename board manifest too, `ATMEGA48PB.json` -> `ATmega48PB.json`?
- What are the files `at90can128` and similar to them?

**Comment by MCUdude** [comment]
> Could we rename board manifest too, ATMEGA48PB.json -> ATmega48PB.json?

sorry, git didn't catch the name change since it was only a change in capital/non capital letters. Should be fixed now.

 > What are the files at90can128 and similar to them?

The AT90CAN32/64/128 are *very* similar to ATmega64, ATmega128, and ATmega1281, but has hardware CAN support. They are pin compatible with ATmega64/128/1281, but they need a dedicated boards manifest file.

**Comment by ivankravets** [comment]
Thanks! 😊

**Comment by MCUdude** [comment]
Awesome! I'll update the documentation for MegaCore, MiniCore and MightyCore

**Pull request merged**
