### PR TITLE
Add support for Sleepy Pi board

### PR DESCRIPTION
**Pull request by arunderwood**
## Changes

* Add a new board for the [Sleepy Pi 2](https://spellfoundry.com/product/sleepy-pi-2/)
* Update code to use GPIO pin 22 for the serial DTR command to reset the atmega328p

I had originally created a [forum post](https://community.platformio.org/t/flashing-sleepypi-with-gpio-dtr/2919) for this, but I decided to push ahead with my own attempt.

## Extra info
* How to reset the DTR pin with a [hacked up avrdude](https://spellfoundry.com/sleepy-pi/setting-arduino-ide-raspbian/#Setting_up_the_Reset_DTR_pin)
* [Board description for the Sleepy Pi 2](https://github.com/SpellFoundry/Sleepy-Pi-Setup/blob/master/boards.txt)

## Notes

I have not tested this yet, but I'm starting the PR incase there is feedback.  I will comment again once I have tested this. **UPDATE: I tested this and it does work with a Sleepy Pi 2.**

### CODE REVIEW

**Comment by arunderwood** [comment]
This is ready for review.

**Comment by ivankravets** [comment]
Thank you very much!

**Comment by arunderwood** [comment]
Thank you.  Is there a release cycle for when new releases are tagged?

**Comment by ivankravets** [comment]
I'll release it this week. Nevertheless, you can use dev/version
```
[env:...]
platform = https://github.com/platformio/platform-atmelavr.git
board = ...
```

**Comment by arunderwood** [comment]
Excellent.  Thanks!

**Comment by njbuch** [comment]
Awesome work! Is there an example platform.ini that works from a Raspberry Pi or further info to look at?

**Comment by arunderwood** [comment]
Here is the one I'm using, which also pulls in some of the SleepyPi libs

```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:iphotrod]
platform = atmelavr
board = sleepypi
framework = arduino
upload_port = /dev/ttyS0

lib_deps =
     Time@1.5
     Low-Power@1.6
     https://github.com/SpellFoundry/SleepyPi2.git#def9d3828ee1a777727d350588887a929b8b77a6
     https://github.com/SpellFoundry/PCF8523.git#bd81fce78a374e5a444d9017a2dc922e40ee0c72
```

If someone can point out a place in the PIO docs to add info for specific boards I can try to fill it out a bit with my experiences.

**Comment by njbuch** [comment]
Thank you, tried this evening, without success.

1. Installed platformio 3.5.1
2. Copied your platform.ini file
3. Copied some simple code to main.cpp
4. Ran a command to find serialport, and edited the platform.ini
`
pi@raspberrypi:~/sketchbook/RC_Ard_v2 $ platformio serialports list
/dev/ttyAMA0
------------
Hardware ID: 3f201000.serial
Description: ttyAMA0
`
5. Ran "platformio run --target upload", and got:
`
Indexing .pioenvs/RC_Ard_v2/lib073/libPCF8523.a
Linking .pioenvs/RC_Ard_v2/firmware.elf
Checking program size
text       data     bss     dec     hex filename
3456         40     328    3824     ef0 .pioenvs/RC_Ard_v2/firmware.elf
Building .pioenvs/RC_Ard_v2/firmware.hex
Looking for upload port...
Use manually specified: /dev/ttyAMA0
*** [upload] Device or resource busy
======================================== [ERROR] Took 24.12 seconds ========================================
pi@raspberrypi:~/sketchbook/RC_Ard_v2 $

`

**Comment by arunderwood** [comment]
Ahh, yep I missed an important piece of info about my setup.  I have not yet found a way to get the mechanism PIO uses to trip the GPIO connected to the DTR pin on the SleepyPi to work as a non-root user. 
It _should_ work for a user that is a member of the __gpio__ group, but I have not found that to be the case.

In lieu of a proper solution, I have been running PIO flash operations as root.  It's bad practice but I haven't had time to loop back and properly investigate.

Try `sudo platformio run --target upload`

**Comment by arunderwood** [comment]
Also, the serial port mapping will vary depending on whether you're on an RPi 3 or not.  On a 3, the serial port is `/dev/ttyS0`.  On earlier models, it's `/dev/ttyAMA0`.  This is because they attached the new BT chip to the hardware UART in the RPi 3.

https://spellfoundry.com/2016/05/29/configuring-gpio-serial-port-raspbian-jessie-including-pi-3/

I modified the SpellFoundry setup script to do a lot of the setup I wanted to use PIO instead of the Arduino IDE.  You can check that out here:

https://github.com/arunderwood/iphotrod-arduino/blob/master/Sleepy-Pi-Setup.sh

At some point I should probably break that provisioning script out into it's own repo.

**Comment by njbuch** [comment]
Ran your setup-script, and now it works, really well I must say! Thanks, you made my day! :)

**Pull request merged**
